#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WebKey.Resource", IsApplication=true)]

namespace WebKey
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int btn_circle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int icon_0 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int icon_1 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int icon_2 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int icon_3 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int icon_4 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int icon_add = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int icon_email = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int icon_import = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int icon_settings = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07001c
			public const int action_add = 2131165212;
			
			// aapt resource value: 0x7f07001b
			public const int action_email = 2131165211;
			
			// aapt resource value: 0x7f07001d
			public const int action_import = 2131165213;
			
			// aapt resource value: 0x7f07001e
			public const int action_reset_pass = 2131165214;
			
			// aapt resource value: 0x7f070004
			public const int add_btn_back = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int add_btn_save = 2131165187;
			
			// aapt resource value: 0x7f070007
			public const int add_detail = 2131165191;
			
			// aapt resource value: 0x7f070001
			public const int add_header = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int add_scroll_view = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int add_view_bottom = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int add_view_top = 2131165184;
			
			// aapt resource value: 0x7f070010
			public const int btnCancel = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int btnProceed = 2131165201;
			
			// aapt resource value: 0x7f07000b
			public const int detail_btn_back = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int detail_btn_delete = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int detail_btn_edit = 2131165193;
			
			// aapt resource value: 0x7f07000d
			public const int detail_detail = 2131165197;
			
			// aapt resource value: 0x7f07000c
			public const int detail_scroll_view = 2131165196;
			
			// aapt resource value: 0x7f070008
			public const int detail_view_bottom = 2131165192;
			
			// aapt resource value: 0x7f070006
			public const int myLayout = 2131165190;
			
			// aapt resource value: 0x7f070014
			public const int reg_btnCancel = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int reg_btnProceed = 2131165205;
			
			// aapt resource value: 0x7f070013
			public const int reg_textPasswordConfirm = 2131165203;
			
			// aapt resource value: 0x7f070012
			public const int reg_txtPassword = 2131165202;
			
			// aapt resource value: 0x7f07001a
			public const int reset_btnCancel = 2131165210;
			
			// aapt resource value: 0x7f070019
			public const int reset_btnProceed = 2131165209;
			
			// aapt resource value: 0x7f070018
			public const int reset_new_confirm_password = 2131165208;
			
			// aapt resource value: 0x7f070017
			public const int reset_new_password = 2131165207;
			
			// aapt resource value: 0x7f070016
			public const int reset_old_password = 2131165206;
			
			// aapt resource value: 0x7f07000e
			public const int textSearch = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int txtPassword = 2131165199;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int AddEdit = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Detail = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int HomeList = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Login = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Register = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int ResetPassActivity = 2130968581;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int master_menu = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_action_content_new = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int menu_add = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int menu_email = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int menu_import = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int menu_reset = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
